# We need this intention allow to be created from mc to postgres before the terraform apply code is run so as to prevent
# the mc nomad job from failing(when consul acl default policy is set to deny). The mc nomad job creates buckets in postgres
# and it fails at that stage if the explicit allow intentions are not already in place.
- name: set variable
  set_fact:
    consul_token: "{{ lookup('env', 'consul_master_token') }}"

- name: Check if intention postgres-local => postgres (allow) exists
  shell: consul intention match -source postgres-local
  register: postgres_local_intention
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'
  environment:
      CONSUL_HTTP_TOKEN: "{{ consul_token }}"

- name: Create intention for proxy between postgres-local and postgres
  shell: consul intention create postgres-local postgres
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'
  environment:
      CONSUL_HTTP_TOKEN: "{{ consul_token }}"
