- name: Generate Secrets with Vault
  shell: |
      vault kv put secret/postgres \
      username=$(vault write -field='value' gen/password length=12 symbols=0) \
      password=$(vault write -field='value' gen/password length=12 symbols=0)
  run_once: true
  environment:
      VAULT_ADDR: "http://127.0.0.1:8200"
