- name: Generate Secrets with Vault
  shell: |
      vault kv put secret/postgres \
      username=$(vault write -field='value' gen/password length=12 symbols=0) \
      password=$(vault write -field='value' gen/password length=12 symbols=0)
  run_once: true
  environment:
      VAULT_ADDR: "http://127.0.0.1:8200"

- name: Register username key
  shell:
      cmd: vault kv get -field='username' secret/postgres
  register: username

- name: Register password key
  shell:
      cmd: vault kv get -field='password' secret/postgres
  register: password

- name: Delete /etc/default/terraform.tfvars if it exists
  file:
      path: /etc/default/terraform.tfvars
      state: absent

- name: Add username and password to the /etc/default/terraform.tfvars file
  shell: |
      echo username='"{{ username.stdout }}"' >> /etc/default/terraform.tfvars
      echo password='"{{ password.stdout }}"' >> /etc/default/terraform.tfvars
  run_once: true
