- name: Generate random strings for username and password for Postgres
  set_fact:
      username: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12') }}"
      password: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=12') }}"

- name: Generate Secrets with Vault
  shell: vault kv put secret/postgres username="{{ username }}" password="{{ password }}"
  run_once: true
  environment:
      VAULT_ADDR: "{{ lookup('env', 'VAULT_ADDR') }}"
      VAULT_TOKEN: "{{ lookup('env', 'vault_master_token') }}"
  register: secrets
