- name: Terraform
  terraform:
    project_path: ../../example/postgres_standalone
    force_init: true
    state: present
  register: terraform

- name: Terraform stdout
  debug:
    msg: "{{terraform.stdout}}"