- name: set variable
  set_fact:
    consul_token: "{{ lookup('env', 'consul_master_token') }}"

- name: Postgres healthchecks pass
  uri:
    url: http://localhost:8500/v1/health/checks/postgres?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  when: not lookup('env', 'consul_acl') | bool
  register: result_postgres
  retries: 15
  delay: 15
  until: result_postgres.json | length == 1
  tags: test

- name: Postgres healthchecks pass with token
  uri:
    url: http://localhost:8500/v1/health/checks/postgres?filter={{ '(Status=="passing")' | urlencode }}
    method: GET
    headers:
      X-Consul-Token: "{{ consul_token }}"
    return_content: yes
    status_code: 200
    body_format: json
  when: lookup('env', 'consul_acl') | bool and lookup('env', 'consul_acl_default_policy') == 'deny'